[WIP] Use OpenShift and Thoth Common api
- get rid of the need to use oc tool completely (replaced by kubernetes
python api)
- replace auth api by config api

Signed-off-by: Marek Cermak <macermak@redhat.com>

deleted:    osiris/apis/auth.py
deleted:    osiris/schema/auth.py
new file:   osiris/apis/config.py
new file:   osiris/schema/config.py
modified:   .s2i/action_hooks/deploy
modified:   osiris/apis/__init__.py

diff --git a/.s2i/action_hooks/deploy b/.s2i/action_hooks/deploy
--- a/.s2i/action_hooks/deploy
+++ b/.s2i/action_hooks/deploy
@@ -25,32 +25,32 @@ pwd
 
 # Download and Install oc client
 
-OC_TOOL_RELEASE="v3.11.0"
-OC_TOOL_FILE_NAME="openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit"
-OC_TOOL_BIN_DIR="${APP_ROOT}/oc-tool"
-
-TMP_DIR=$( mktemp -d --suffix "oc-tool" )
-
-
-pushd ${TMP_DIR}
-
-echo " -----> Downloading OC Tool."
-
-curl -fLsS "https://github.com/openshift/origin/releases/download/${OC_TOOL_RELEASE}/${OC_TOOL_FILE_NAME}.tar.gz" -o "${OC_TOOL_FILE_NAME}.tar.gz"
-tar -xvf "${OC_TOOL_FILE_NAME}.tar.gz"
-
-echo " -----> Installing OC Tool."
-
-mkdir -p ${OC_TOOL_BIN_DIR}
-mv ${OC_TOOL_FILE_NAME} ${OC_TOOL_BIN_DIR}
-
-ln -s ${OC_TOOL_BIN_DIR}/*/oc ${APP_ROOT}/bin/oc
-
-which oc
-
-[[ $? -eq 0 ]] && echo " -----> OC Tool Installation finished successfully." \
-               || echo " -----> OC Tool Installation failed."
-
-popd
-
-rm -rf ${TMP_DIR}
+# OC_TOOL_RELEASE="v3.11.0"
+# OC_TOOL_FILE_NAME="openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit"
+# OC_TOOL_BIN_DIR="${APP_ROOT}/oc-tool"
+#
+# TMP_DIR=$( mktemp -d --suffix "oc-tool" )
+#
+#
+# pushd ${TMP_DIR}
+#
+# echo " -----> Downloading OC Tool."
+#
+# curl -fLsS "https://github.com/openshift/origin/releases/download/${OC_TOOL_RELEASE}/${OC_TOOL_FILE_NAME}.tar.gz" -o "${OC_TOOL_FILE_NAME}.tar.gz"
+# tar -xvf "${OC_TOOL_FILE_NAME}.tar.gz"
+#
+# echo " -----> Installing OC Tool."
+#
+# mkdir -p ${OC_TOOL_BIN_DIR}
+# mv ${OC_TOOL_FILE_NAME} ${OC_TOOL_BIN_DIR}
+#
+# ln -s ${OC_TOOL_BIN_DIR}/*/oc ${APP_ROOT}/bin/oc
+#
+# which oc
+#
+# [[ $? -eq 0 ]] && echo " -----> OC Tool Installation finished successfully." \
+#                || echo " -----> OC Tool Installation failed."
+#
+# popd
+#
+# rm -rf ${TMP_DIR}
